-- tạo service
[oracle@oraclesv02 hddtNew]$ sqlplus / as sysdba

SQL> show pdbs

    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 ORCL_PLUG                      READ WRITE NO
         4 PDB_HDDT                       READ WRITE NO
SQL> alter session set container=orcl_plug;

--Tao service
SQL> exec dbms_service.create_service('HR', 'HR.exam.com')

PL/SQL procedure successfully completed.

--start service
SQL> exec dbms_service.start_service('HR')

PL/SQL procedure successfully completed.

--kiem tra service qua listenner
[oracle@oraclesv02 root]$ lsnrctl status

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 01-FEB-2024 09:39:02      

Copyright (c) 1991, 2022, Oracle.  All rights reserved.

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oraclesv02)(PORT=1521)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
Start Date                31-JAN-2024 10:24:00
Uptime                    0 days 23 hr. 15 min. 1 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /u01/app/oracle/product/19.0.0/dbhome_1/network/admin/listener.ora
Listener Log File         /u01/app/oracle/diag/tnslsnr/oraclesv02/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=oraclesv02)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=oraclesv02)(PORT=5500))(Security=(my_wallet_directory=/u01/app/oracle/admin/orclcdb/xdb_wallet))(Presentation=HTTP)(Session=RAW))
Services Summary...
Service "0d9047a4f4805a3ee063650a0a0a4c93" has 1 instance(s).
  Instance "orclcdb", status READY, has 1 handler(s) for this service...
Service "1036ae06ba711344e063650a0a0a0f88" has 1 instance(s).
  Instance "orclcdb", status READY, has 1 handler(s) for this service...
Service "86b637b62fdf7a65e053f706e80a27ca" has 1 instance(s).
  Instance "orclcdb", status READY, has 1 handler(s) for this service...
Service "HR.exam.com" has 1 instance(s).
  Instance "orclcdb", status READY, has 1 handler(s) for this service...
Service "orcl_plug" has 1 instance(s).
  Instance "orclcdb", status READY, has 1 handler(s) for this service...
Service "orclcdb" has 1 instance(s).
  Instance "orclcdb", status READY, has 1 handler(s) for this service...
Service "orclcdbXDB" has 1 instance(s).
  Instance "orclcdb", status READY, has 1 handler(s) for this service...
Service "pdb_hddt" has 1 instance(s).
  Instance "orclcdb", status READY, has 1 handler(s) for this service...
The command completed successfully
[oracle@oraclesv02 root]$

-- ket noi vao server tu remot qua service
sqlplus hr/hr@10.10.10.101:1521/HR.exam.com


--set lai dang ky listener
show Parameter local;
alter system set local_listener='(ADDRESS=(PROTOCOL=tcp)(HOST=10.10.10.101)(PORT=1521))';
alter system register;

--tool:
netca;


--===============================================
--tao listenner
# listener.ora Network Configuration File: /u01/app/oracle/product/19.0.0/dbhome_1/network/admin/listener.ora
# Generated by Oracle configuration tools.

LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = oraclesv02)(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )

LISTENER2 =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = oraclesv02)(PORT = 1621))
    )
  )
#load blance
  LISTENER3 =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = oraclesv02)(PORT = 1621))
      (ADDRESS = (PROTOCOL = TCP)(HOST = oraclesv02)(PORT = 1521))
    )
  )

-- dang ky listenner voi he thong
show Parameter local;
alter system set local_listener='LISTENER_ORCLCDB, (ADDRESS=(PROTOCOL=tcp)(HOST=oraclesv02)(PORT=1621))';
alter system set local_listener='(ADDRESS=(PROTOCOL=tcp)(HOST=oraclesv02)(PORT=1521)), (ADDRESS=(PROTOCOL=tcp)(HOST=oraclesv02)(PORT=1621))';
alter system register;
~
---===================================================
-- Thong ke connection qua listenner
cd /u01/app/oracle/diag/tnslsnr/oraclesv02/listener/trace

fgrep "01-FEB-2024" algolsn.log | fgrep establish | awk '{print $1 " "} $2' | awk -F: '{print $1 ":" $2}' | sort | uniq -c

fgrep "01-FEB-2024:" listener.log | fgrep "establish" | awk '{print $1 " "} $2' | awk -F: '{print $1 ":" $2}' | sort | uniq -c 

